on:
  pull_request:
    branches:
      - "main"

jobs:
  linux:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          GOOS=linux GOARCH=amd64 go build -o . github.com/xvzc/SpoofDPI/cmd/spoof-dpi && tar -zcvf spoof-dpi-linux.tar.gz ./spoof-dpi 
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.tar.gz
