# on:
#   push:
#     branches:
#       - "main"

# jobs:
#   linux:
#     name: "Release"
#     runs-on: "ubuntu-latest"

#     steps:
#       # ...
#       - name: "Build & test"
#         run: |
#           ls -al && pwd && ls -al .. && GOOS=linux GOARCH=amd64 go build ./cmd/... && tar -zcvf spoof-dpi-linux.tar.gz ./spoof-dpi
#       - uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           repo_token: "${{ secrets.PERSONAL_TOKEN }}"
#           automatic_release_tag: "latest"
#           prerelease: true
#           title: "Development Build"
#           files: |
#             *.tar.gz

# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        goos: linux
        goarch: amd64
